CRMRetail/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using m = CRMRetail.Modelos;

namespace CRMRetail.Controllers
{
    public class ProductosController : Utilidades.Comun
    {
        public ActionResult Index()
        {
            List<m.Producto> productos = n.producto.Producto_Seleccionar();

            ViewBag.Poductos = productos;
            return View();
        }
        [HttpPost]
        public JsonResult Producto_Seleccionar_Id(m.Producto producto)
        {
            m.Producto producto1 = n.producto.Producto_Seleccionar_Id(producto);
            m.PromocionProducto promocionProducto = n.promocionProducto.PromocionProducto_Seleccionar_IdProducto(producto);
            m.ArticuloImg articuloImg = n.articuloImg.ProductoImg_Seleccionar_IdProducto(producto);

            Validacion jsonObject = new Validacion()
            {
                Producto = new 
                {
                    Id = producto1.Id,
                    Nombre = producto1.Nombre,
                    SKU = producto1.SKU,
                    Descripcion = producto1.Descripcion,
                    PrecioDistribuidor = producto1.PrecioDistribuidor,
                    PrecioPublico = producto1.PrecioPublico,
                    PrecioDemo = producto1.PrecioDemo,
                    Activo = producto1.Activo,
                    IdCategoria = producto1.IdCategoria,
                    Categoria = producto1.Categoria
                },
                Promocion = new
                {
                    FechaInicio = promocionProducto.FechaInicio,
                    FechaFin = promocionProducto.FechaFin,
                    Precio = promocionProducto.Precio
                },
                ProductoImg = new {
                    Descripcion = articuloImg.Descripcion
                }
            };


            return Json(jsonObject);
        }


        public class Validacion
        {
            public object Producto { get; set; }
            public object Promocion { get; set; }
            public object ProductoImg { get; set; }
        }

        /// <summary>
        /// CARGA DE NUEVOS PRODUCTOS
        /// </summary>
        /// <returns></returns>
        public ActionResult Agregar()
        {
            return View();
        }

        [HttpPost]
        public JsonResult CargaImagen(m.Control_Archivos control_Archivos)
        {
            string DirectorioUsuario = Server.MapPath("~") + "\\ProductosImagenes\\";
            string DirectorioURL = System.Web.HttpContext.Current.Request.Url.Authority + "\\ProductosImagenes\\";

            List<m.ArticuloImg> LstArticuloImg = new List<m.ArticuloImg>();

            if (Session["Imagenes"] != null)
            {
                LstArticuloImg = (List<m.ArticuloImg>)Session["Imagenes"];
            }

            for (int i = 0; i < Request.Files.Count; i++)
            {
                HttpPostedFileBase file = Request.Files[i];
                m.ArticuloImg _artiucloImg = new m.ArticuloImg();
                _artiucloImg = NuevoArchivo(file, DirectorioUsuario, DirectorioURL);

                if (_artiucloImg.NmArchivo != null)
                {
                    LstArticuloImg.Add(_artiucloImg);
                }
            }

            Session["Imagenes"] = LstArticuloImg;

            return Json(LstArticuloImg);
        }

        public m.ArticuloImg NuevoArchivo(HttpPostedFileBase Archivo, string DirectorioUsuario, string DirectorioURL)
        {
            m.ArticuloImg _inmueblesImg = new m.ArticuloImg();
            String FileExtension = Path.GetExtension(Archivo.FileName).ToLower();

            if (!Directory.Exists(DirectorioUsuario))
            {
                Directory.CreateDirectory(DirectorioUsuario);
            }

            if (".jpg".Contains(FileExtension) ^ ".png".Contains(FileExtension) ^ ".jpeg".Contains(FileExtension))
            {

                m.Control_Archivos archivo = n.control_archivos.NuevoArchivo();
                string NombreArchivo = archivo.Id.ToString().PadLeft(12, '0');

                Image image = ResizeImage(Image.FromStream(Archivo.InputStream, true, true), 640, 640);
                image.Save(DirectorioUsuario + NombreArchivo + FileExtension);

                _inmueblesImg.IdArchivo = archivo.Id;
                _inmueblesImg.NmArchivo = NombreArchivo + FileExtension;
                _inmueblesImg.NmOriginal = Archivo.FileName;
                _inmueblesImg.Activo = 1;
                _inmueblesImg.Descripcion = DirectorioURL + NombreArchivo + FileExtension;

            }

            return _inmueblesImg;
        }

        public static Image ResizeImage(Image srcImage, int newWidth, int newHeight)
        {
            using (Bitmap imagenBitmap = new Bitmap(newWidth, newHeight, PixelFormat.Format32bppRgb))
            {
                imagenBitmap.SetResolution(
                   Convert.ToInt32(srcImage.HorizontalResolution),
                   Convert.ToInt32(srcImage.HorizontalResolution));

                using (Graphics imagenGraphics = Graphics.FromImage(imagenBitmap))
                {
                    imagenGraphics.SmoothingMode = SmoothingMode.AntiAlias;
                    imagenGraphics.InterpolationMode = InterpolationMode.HighQualityBicubic;
                    imagenGraphics.PixelOffsetMode = PixelOffsetMode.HighQuality;
                    imagenGraphics.DrawImage(srcImage, new Rectangle(0, 0, newWidth, newHeight), new Rectangle(0, 0, srcImage.Width, srcImage.Height), GraphicsUnit.Pixel);
                    MemoryStream imagenMemoryStream = new MemoryStream();
                    imagenBitmap.Save(imagenMemoryStream, ImageFormat.Jpeg);
                    srcImage = Image.FromStream(imagenMemoryStream);
                }
            }
            return srcImage;
        }

        [HttpPost]
        public JsonResult OrdenarImagenes(m.NuevoArticuloImg nuevoArticuloImg)
        {
            List<m.ArticuloImg> LstArticuloImg = new List<m.ArticuloImg>();
            List<m.ArticuloImg> LstArticuloImgNuevo = new List<m.ArticuloImg>();

            if (Session["Imagenes"] != null)
            {
                LstArticuloImg = (List<m.ArticuloImg>)Session["Imagenes"];
            }

            // TOMA LA IMAGEN ESCOGIDA
            for (int i = 0; i < LstArticuloImg.Count; i++)
            {
                if (LstArticuloImg[i].IdArchivo == nuevoArticuloImg.ArticuloImg.IdArchivo)
                {
                    LstArticuloImgNuevo.Add(LstArticuloImg[i]);
                }
            }

            // LLEGA EL LSITADO
            for (int i = 0; i < LstArticuloImg.Count; i++)
            {
                if (LstArticuloImg[i].IdArchivo != nuevoArticuloImg.ArticuloImg.IdArchivo)
                {
                    LstArticuloImgNuevo.Add(LstArticuloImg[i]);
                }
            }

            Session["Imagenes"] = LstArticuloImgNuevo;

            return Json(LstArticuloImgNuevo);
        }

        [HttpPost]
        public JsonResult EliminarImagen(m.NuevoArticuloImg nuevoArticuloImg)
        {
            string DirectorioUsuario = Server.MapPath("~") + "\\ProductosImagenes\\";
            List<m.ArticuloImg> LstArticuloImg = new List<m.ArticuloImg>();
            if (Session["Imagenes"] != null)
            {
                LstArticuloImg = (List<m.ArticuloImg>)Session["Imagenes"];
            }

            for (int i = 0; i < LstArticuloImg.Count; i++)
            {
                if (LstArticuloImg[i].IdArchivo == nuevoArticuloImg.ArticuloImg.IdArchivo)
                {
                    System.IO.File.Delete(DirectorioUsuario + LstArticuloImg[i].NmArchivo);
                    LstArticuloImg.Remove(LstArticuloImg[i]);
                }
            }

            Session["Imagenes"] = LstArticuloImg;

            return Json(LstArticuloImg);
        }

        [HttpPost]
        public JsonResult BuscarSKU(m.Producto producto)
        {
            m.Producto producto1 = n.producto.Producto_Seleccionar_SKU(producto.SKU);
            m.Mensaje mensaje = new m.Mensaje();

            if(producto1.Id > 0)
            {   
                mensaje.Respuesta = true;
                mensaje.RespuestaText = producto1.SKU;
            }
            else
            {
                mensaje.Respuesta = false;
                mensaje.RespuestaText = producto1.SKU;
            }

            return Json(producto1);
        }

        [HttpPost]
        public JsonResult RegistraNuevo_Articulo(m.Producto producto)
        {
            List<m.ArticuloImg> LstArticuloImg = new List<m.ArticuloImg>();
            m.Mensaje mensaje = new m.Mensaje();

            if (Session["Imagenes"] != null)
            {
                LstArticuloImg = (List<m.ArticuloImg>)Session["Imagenes"];
            }

            if (LstArticuloImg.Count > 0)
            {

                if (String.IsNullOrEmpty(producto.Descripcion))
                {
                    producto.Descripcion = "";
                }
                if (String.IsNullOrEmpty(producto.PrecioDemo.ToString()))
                {
                    producto.PrecioDemo = 0;
                }

                // REGISTRAR EL PORODUCTO.
                mensaje = n.producto.Producto_Agregar(producto);
                
                if (mensaje.Respuesta)
                {
                    // REGISTRAR LA PROMOCION SI EXISTE.
                    if (producto.Precio > 0)
                    {
                        m.PromocionProducto promocionProducto = new m.PromocionProducto();
                        promocionProducto.FechaInicio = producto.FechaInicio;
                        promocionProducto.FechaFin = producto.FechaFin;
                        promocionProducto.Precio = producto.Precio;

CRMRetail/Views/Administracion/Catalogos.cshtml
@{
    ViewBag.Title = "Catalogos";
}

<script src="~/assets/js/plugin/datatables/datatables.min.js"></script>
<link href="~/assets/css/jquery.dataTables.min.css" rel="stylesheet" />

<script>

    $(document).ready(function () {

        $('#IndexCatalogos').addClass("nav-item active submenu");

        $('#tabla01').DataTable({
            "searching": false,
            "paging": false,
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
            },
            info: false,
        });

        var obtenerParametrodeURL = function getUrlParameter(sParam) {
            var sPageURL = window.location.search.substring(1),
                sURLVariables = sPageURL.split('&'),
                sParameterName,
                i;

            for (i = 0; i < sURLVariables.length; i++) {
                sParameterName = sURLVariables[i].split('=');

                if (sParameterName[0] === sParam) {
                    return sParameterName[1] === undefined ? true : decodeURIComponent(sParameterName[1]);
                }
            }
        };

        var idd = obtenerParametrodeURL('id');
        if (idd == 1) {
            $('#o1').addClass('active show');
        }
        else if (idd == 2) {
            $('#o2').addClass('active show');
        }
        else if (idd == 3) {
            $('#o3').addClass('active show');
        }
        else if (idd == 4) {
            $('#o4').addClass('active show');
        }
        else if (idd == 5) {
            $('#o5').addClass('active show');
        }
        else if (idd == 6) {
            $('#o6').addClass('active show');
        }

    });
</script>

<style>
    table.dataTable thead tr {
        background-color: #1a2035;
        color: white
    }

    .header th {
        height: 25px;
        line-height: 2px;
    }
</style>

<div class="page-inner">
    <div class="page-header">
        <h4 class="page-title">Catálogos</h4>
    </div>
    <div class="row">

        <div id="Espera" style="display:none; width:69px;height:90px;position:absolute;top:20%;left:50%;padding:2px;z-index:1000">
            <img src="../assets/img/spinner.gif" width="64" height="64" /><br />Cargando...
        </div>
    </div>

    <div class="card">

        <div class="card-body">

            <div class="row">

                <div class="col-md-12">

                    @Html.Partial("_MenuCatalogos")

                </div>

            </div>

        </div>

    </div>

    <div class="row">

        <div class="col-md-6">

            <div class="card">
                <form method="post" action="Catalogos" id="catalogosForm">
                    <div class="card-body">
                        <div class="form-group">
                            <input type="hidden" name="tabla" value="@ViewBag.NombreTabla" />
                            <label for="nombre">Nombre:</label>
                            <input type="text" name="nombre" class="form-control" autocomplete="off" required/>
                        </div>
                    </div>

                    <div class="card-action">
                        <button type="submit" class="btn btn-primary" id="agregarBtn">Agregar</button>
                    </div>
                </form>
            </div>


        </div>

        <div class="col-md-6">

            <div class="card">

                <div class="card-body">
                    
                    <div class="table-responsive">
                        <table id="tabla01" class="display compact table-striped table-hover" style="width:60%">
                            <thead class="header">
                                <tr>
                                    <th>Nombre</th>
                                    <th style="text-align: center;">Eliminar</th>
                                </tr>
                            </thead>
                            <tbody>

                                @if (ViewBag.Tabla == null)
                                {
                                    <tr><td colspan="3" align="center">Sin datos para mostrar</td></tr>
                                }
                                else
                                {
                                    foreach (var items in ViewBag.Tabla)
                                    {

                                        <tr>
                                            <td>@items.Nombre </td>
                                            <td style="text-align: center; cursor:pointer">
                                                <a>
                                                    <i onclick="Eliminar('@items.Id', '@ViewBag.NombreTabla')" class="fa fa-trash" aria-hidden="true" style="color: red;"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                }

                            </tbody>
                        </table>
                    </div>


                </div>

            </div>

        </div>


    </div>



</div>

<script>
    $(document).ready(function () {
        $('#catalogosForm').submit(function (e) {
            var idParam = getParameterByName('id', window.location.href);
            if (!idParam) {
                e.preventDefault(); // Evita que el formulario se envíe
                $.notify({
                    //icon: 'fa fa-paw',
                    message: 'Selecciona un catálogo'
                }, {
                    type: 'danger',
                    allow_dismiss: false,
                    animate: {
                        enter: 'animated rollIn',
                        exit: 'animated rollOut'
                    }
                });
            }
        });

        // Función para obtener el valor de un parámetro de la URL
        function getParameterByName(name, url) {
            if (!url) {
                url = window.location.href;
            }
            name = name.replace(/[\[\]]/g, '\\$&');
            var regex = new RegExp('[?&]' + name + '(=([^&#]*)|&|#|$)');
            var results = regex.exec(url);
            if (!results) {
                return null;
            }
            if (!results[2]) {
                return '';
            }
            return decodeURIComponent(results[2].replace(/\+/g, ' '));
        }
    });

    function Eliminar(id, tabla) {

        $.ajax({
            url: "/Administracion/Eliminar",
            type: "POST",
            data: { id: id, tabla: tabla },
            success: function (data) {
                swal({
                    text: 'Se guardó el registro exitosamente 1.',
                    icon: 'success',
                    buttons: {
                        confirm: {
                            className: 'btn btn-success'
                        }
                    }
                });
                location.reload(); 
            },
            error: function (xhr, textStatus, errorThrown) {
                swal({
                    text: 'Se guardó el registro exitosamente 2.',
                    icon: 'success',
                    buttons: {
                        confirm: {
                            className: 'btn btn-success'
                        }
                    }
                });
                location.reload(); 
            }

        });
    }

</script>

CRMRetail/Views/Administracion/Index.cshtml
@{
    ViewBag.Title = "Index";
}



<div class="page-inner">
    <div class="page-header">
        <h4 class="page-title">Administración General del Sistema</h4>
    </div>
    <div class="row">

        <div id="Espera" style="display:none; width:69px;height:90px;position:absolute;top:20%;left:50%;padding:2px;z-index:1000">
            <img src="../assets/img/spinner.gif" width="64" height="64" /><br />Cargando...
        </div>
    </div>

    <div class="card">

        <div class="card-body">

            <div class="row">

                <div class="col-md-12">

                    @Html.Partial("_MenuAdmin")
                </div>

            </div>

        </div>

    </div>

    <div class="card">

        <div class="card-body">

            <div class="row">




            </div>

        </div>

    </div>


</div>

<script>$('#IndexAdmin').addClass("nav-item active submenu");</script>

CRMRetail/Views/Administracion/Ofertas.cshtml
<style>
    table.dataTable thead tr {
        background-color: #1a2035;
        color: white
    }

    .header th {
        height: 25px;
        line-height: 2px;
    }
</style>

<div class="page-inner">
    <div class="page-header">
        <h4 class="page-title">Ofertas</h4>
    </div>
    <div class="row">

        <div id="Espera" style="display:none; width:69px;height:90px;position:absolute;top:20%;left:50%;padding:2px;z-index:1000">
            <img src="../assets/img/spinner.gif" width="64" height="64" /><br />Cargando...
        </div>
    </div>

    <div class="card">

        <div class="card-body">

            <div class="row">

                <div class="col-md-12">
                    @Html.Partial("_MenuAdmin")
                </div>

            </div>

        </div>

    </div>

    <div class="card">

        <div class="card-body">

           
            <div class="row">


                <div class="table-responsive">
                    <table id="tabla01" class="display compact hover table-striped table-hover text-center" style="width:100%;">
                        <thead class="header">
                            <tr>
                                <th>Nombre</th>
                                <th>SKU</th>
                                <th>Categoría </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                            foreach (var dtProducto in ViewBag.Poductos)
                            {
                            <tr>
                                <td>@dtProducto.Nombre</td>
                                <td>@dtProducto.SKU</td>
                                <td>@dtProducto.Categoria</td>
                                <td>
                                    <button type="button" class="btn btn-icon btn-link" onclick="AgregarOferta(@dtProducto.Id)">
                                        <i class="fa fa-plus-square"></i>
                                    </button>
                                </td>
                            </tr>
                            }
                            }
                        </tbody>
                    </table>
                </div>


            </div>

        </div>

    </div>


</div>


<div class="modal fade" id="ModalNuevo" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="ModalLabel"></h3>
                <input type="text" id="Id" style="display:none">

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">



                <div class="row">
                    <div class="col-md-6 col-lg-6">

                        <div class="form-group">
                            <label for="nNombre" class="col-md-3 col-form-label fc-left">Precio:</label>
                            
                                <input type="text" class="form-control form-control" name="nNombre" id="precioPublico" placeholder="" required tabindex="1">
                            
                        </div>

                    </div>
                    <div class="col-md-6 col-lg-6">
                        <div class="form-group">
                            <label for="nRol" class="col-md-3 col-form-label">% descuento:</label>
                                <select class="form-control form-control" id="nRol" name="nRol" required tabindex="7" onchange="Operar(this.value)">
                                    <option value="0">Seleccionar</option>
                                    @foreach (var item in ViewBag.porcentual)
                                    {
                                    <option value="@item.Precio">@item.Nombre</option>
                                    }
                                </select>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-6">
                        <div class="form-group">
                            <label for="largeInput">* Fecha Inicio  </label>
                            <input type="date" class="form-control form-control" id="Fecha_Inicio" required>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-6">
                        <div class="form-group">
                            <label for="largeInput">* Fecha Fin  </label>
                            <input type="date" class="form-control form-control" id="Fecha_Fin" required>
                        </div>
                    </div>
                    <div class="col-md-12 col-lg-12" style="display:none" id="preciohidden">

                        <div class="form-group form-inline">
                            <label for="nNombre" class="col-md-3 col-form-label fc-left">Precio Final:</label>
                            <div class="col-md-9 p-0">
                                <input type="text" class="form-control form-control" name="nNombre" id="precioDescuento" placeholder="" required tabindex="1">
                            </div>
                        </div>

                    </div>

                </div>



                </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success" data-dismiss="modal" onclick="GuardarPromo();">Guardar</button>
                <button type="button" class="btn btn-warning" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>


<script src="~/assets/js/plugin/datatables/datatables.min.js"></script>
<link href="~/assets/css/jquery.dataTables.min.css" rel="stylesheet" />
<script>
    $(document).ready(function () {

        $('#IndexAdmin').addClass("nav-item active submenu");
        $('#o6').addClass('active show');

        $('#tabla01').DataTable({
            "searching": true,
            "paging": true,
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
            },
            info: false,
        });

    });

    function AgregarOferta(id) {
        document.getElementById("nRol").value = 0;
        let miInput = document.getElementById("preciohidden");
        miInput.style.display = "none";

        var obj = {};
        obj['Id'] = id;

        var jsonObject = {
            "producto": obj
        };

        $.ajax({
            url: "@Url.Action("Producto_Seleccionar_Id", "Productos")",
            data: JSON.stringify(jsonObject),
            type: "POST",
            contentType: "application/json",
            dataType: "json",

            success: function (resultado) {
                $('#Id').val(id);
                $('#ModalLabel').text('Agregar promoción a  ' + resultado.Producto.Nombre);
                $('#precioPublico').val(resultado.Producto.PrecioPublico);
            },
            error: function (resultado) {
                alert("Error funcion listar compartir por ID ");
            }
        });

        
        $('#ModalNuevo').modal('show');


    }
    function Operar(Id) {
        let miInput = document.getElementById("preciohidden");
        miInput.style.display = "block";

        let precioInicial = document.getElementById("precioPublico").value;

        let resultado = precioInicial - (precioInicial * Id);

        resultado = resultado.toFixed(2);

        $('#precioDescuento').val(resultado);
    }

    function GuardarPromo() {
        var obj = {};
        obj['Id'] = $('#Id').val();
        obj['FechaInicio'] = $('#Fecha_Inicio').val();
        obj['FechaFin'] = $('#Fecha_Fin').val();
        obj['Precio'] = $('#precioDescuento').val();

        var jsonObject = {
            "producto": obj
        };
        console.log(obj);
        $.ajax({
            url: "@Url.Action("AgregarOferta", "Productos")",
            data: JSON.stringify(jsonObject),
            type: "POST",
            contentType: "application/json",
            dataType: "json",

            success: function (resultado) {
                swal({
                    title: 'CRM Retail',
                    text: 'Promoción Guardada',
                    buttons: {
                        confirm: {
                            className: 'btn btn-success'
                        }
                    },
                })
            },
            error: function (resultado) {
                alert("Error funcion listar compartir por ID ");
            }
        });



    }
</script>