CRMRetail/Controllers/EncuestasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static System.Net.Mime.MediaTypeNames;
using System.Xml.Linq;
using m = CRMRetail.Modelos;


namespace CRMRetail.Controllers
{
    public class EncuestasController : Utilidades.Comun
    {
        // GET: Encuestas
        public ActionResult Index()
        {
            //Datos Venta Id
            int Id = Convert.ToInt32(Request.QueryString["Id"]);

            m.Cliente cliente = new m.Cliente();
            cliente.Id = Id;

            List<m.Encuesta> Lq1 = n.encuesta.List_Cat_q1_t1();
            ViewBag.q1 = Lq1;
            List<m.Encuesta> Lq2 = n.encuesta.List_Cat_q2_t1();
            ViewBag.q2 = Lq2;
            List<m.Encuesta> Lq3 = n.encuesta.List_Cat_q3_t1();
            ViewBag.q3 = Lq3;

            m.Cliente LInfo = n.encuesta.InfoUsuario(cliente);
            ViewBag.InfoUsuario = LInfo;

            return View();
        }

        public ActionResult FormatoEntrega()
        {
            //Datos Venta Id
            int Id = Convert.ToInt32(Request.QueryString["Id"]);
            m.Venta venta = new m.Venta();
            venta.Id = Id;

            m.Cliente cliente = new m.Cliente();
            cliente.Id = Id;

            List<m.Encuesta> Lq1 = n.encuesta.List_Cat_q1_t2();
            ViewBag.q1 = Lq1;

            List<m.Venta> Lventa = n.encuesta.List_venta(venta);
            ViewBag.ListVenta = Lventa;

            m.Cliente LInfo = n.encuesta.InfoUsuario(cliente);
            ViewBag.InfoUsuario = LInfo;


            return View();
        }

        [HttpPost]
        public JsonResult RegistrarEntrega(m.Encuesta DEncuesta)
        {
            m.Encuesta encuesta = n.encuesta.InsertFormatoEntrega(DEncuesta);
            return Json(encuesta);
        }
        
        [HttpPost]
        public JsonResult RegistrarEncuesta(m.Encuesta DEncuesta)
        {
            m.Encuesta encuesta = n.encuesta.InsertEncuestaWeber(DEncuesta);
            return Json(encuesta);
        }
    }
}

CRMRetail/Views/Encuestas/FormatoEntrega.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Formato de Entrega</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Importar CSS de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.7.0"></script>

    <!-- Importar jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Importar JavaScript de Bootstrap -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        .custom-container {
            max-width: 1000px;
            height: auto;
            margin: 0 auto;
            padding: 20px;
            margin-top: 25px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0px 0px 10px rgba(0,0,0,0.3);
        }

        .custom-padding {
            padding-left: 2px;
            padding-right: 2px;
        }
    </style>

</head>
<body>

    <div class="container custom-container">
        <div class="text-center">
            <a><img src="https://i.ibb.co/2dHVrLM/cb589adc50376fda1ebc6e9404b08852-w2500-h1006.png" alt="cb589adc50376fda1ebc6e9404b08852-w2500-h1006" border="0" style="height: 60px; vertical-align:middle; display:inherit"></a>
        </div>
        <br />
        <br />
        <form>
            <div class="row">

                <div class="col-md-4">
                    <div class="form-group">
                        <label for="nombre" class="control-label">Nombre:</label>
                        <input type="text" class="form-control" id="nombre" name="nombre" required value="@ViewBag.InfoUsuario.Nombre">
                    </div>
                </div>


                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Teléfono:</label>
                        <input type="text" class="form-control" id="telefono" name="telefono" required value="@ViewBag.InfoUsuario.TelefonoMovil">
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Dirección:</label>
                        <input type="text" class="form-control" id="direccion" name="direccion" required value="@ViewBag.InfoUsuario.Calle">
                    </div>
                </div>

            </div>
            <hr />

            <div class="text-center">
                <p><b>LOVING GRILL- Distribuidor autorizado Weber confirma la salida de tienda de los siguientes productos:</b></p>

            </div>

            <br />
            <div class="table-responsive">
                <table id="Tproductos" class="table  table-hover " style="width: 100%; cursor: pointer">
                    <thead style="background-color: black">
                        <tr>

                            <th style="color:white">Nombre</th>
                            <th style="color:white; text-align:center;">Cantidad</th>
                            <th style="color: white; text-align: center;">SKU</th>
                            <th style="color: white; text-align: center;">Descripción</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        @foreach (var item in ViewBag.ListVenta)
                        {
                            <tr>
                                <td>@item.Nombre</td>
                                <td class="text-center">@item.Cantidad</td>
                                <td class="text-center">@item.SKU</td>
                                <td class="text-center">@item.Descripcion</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

            <br />
            <hr />


            <div class="row custom-padding">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="q1" class="control-label">
                            1.¿Recibió usted a tiempo su pedido?
                        </label>
                        <select class="form-control" id="q1" required>
                            <option value="">Selecciona una opción</option>
                            @foreach (var item1 in ViewBag.q1)
                            {
                                <option value="@item1.Id">@item1.Nombre</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
            <div class="row custom-padding">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="q2" class="control-label">
                            2.¿Recibió completo su pedido?
                        </label>
                        <select class="form-control" id="q2" required>
                            <option value="">Selecciona una opción</option>
                            @foreach (var item1 in ViewBag.q1)
                            {
                                <option value="@item1.Id">@item1.Nombre</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
            <div class="row custom-padding">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="q3" class="control-label">
                            3.¿Cómo valora usted el servicio recibido?
                        </label>
                        <select class="form-control" id="q3" required>
                            <option value="">Selecciona una opción</option>
                            @foreach (var item1 in ViewBag.q1)
                            {
                                <option value="@item1.Id">@item1.Nombre</option>
                            }
                        </select>
                    </div>
                </div>
            </div>

            <div class="row custom-padding">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="q4" class="control-label">
                            4.¿La persona que le entregó su pedido fue cortés y diligente?
                        </label>
                        <select class="form-control" id="q4" required>
                            <option value="">Selecciona una opción</option>
                            @foreach (var item1 in ViewBag.q1)
                            {
                                <option value="@item1.Id">@item1.Nombre</option>
                            }
                        </select>
                    </div>
                </div>
            </div>

            <div class="row custom-padding">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="q5" class="control-label">
                            5.¿Tuvo que hacer alguna devolución del producto?
                        </label>
                        <select class="form-control" id="q5" required>
                            <option value="">Selecciona una opción</option>
                            <option value="0">No</option>
                            <option value="1">Si</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="text-center">
                <h5>
                    LOVING RILL- Distribuidor Autorizado Weber
                </h5>
                <h5>
                    Av. Universidad 1627, Col. Florida C.P. 01030, Álvaro Obregón CDMX. Tel. 5553220527
                </h5>

                <a class="btn btn-primary" onclick="Guardar();">Guardar</a>
            </div>
        </form>


    </div>



</body>


</html>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {

        $('#Tproductos').DataTable({

            pageLength: 10,
            lengthMenu: [[5, 10, 20, -1], [5, 10, 20, 'Todas']],
            language: {
                url: '//cdn.datatables.net/plug-ins/1.12.1/i18n/es-MX.json'
            }
        });

    });

    function Guardar() {
        var obj = {};
        obj['IdVenta'] = @Request.QueryString["Id"];
        obj['Q1'] = $("#q1 option:selected").val();
        obj['Q2'] = $("#q2 option:selected").val();
        obj['Q3'] = $("#q3 option:selected").val();
        obj['Q4'] = $("#q4 option:selected").val();
        obj['Q5'] = $("#q5 option:selected").val();
        var jsonObject = {
            "DEncuesta": obj
        };
         $.ajax({
            type: "POST",
            url: "@Url.Action("RegistrarEntrega", "Encuestas")",
            async: false,
            data: JSON.stringify(jsonObject),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
             success: function (data) {
                swal({
                    title: "Registro exitoso",
                    text: '',
                    icon: "success",
                    button: "Aceptar",
                }).then((value) => {
                    window.location.href = "https://www.weber.com/MX/es/home/";
                });


            }
        });
    }
</script>

CRMRetail/Views/Encuestas/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Encuesta</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Importar CSS de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <!-- Importar jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Importar JavaScript de Bootstrap -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        .custom-container {
            max-width: 1000px;
            height: auto;
            margin: 0 auto;
            padding: 20px;
            margin-top: 25px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0px 0px 10px rgba(0,0,0,0.3);
        }

        .custom-padding {
            padding-left: 2px;
            padding-right: 2px;
        }
    </style>

</head>
<body>

    <div class="container custom-container">
        <div class="text-center">
            <a><img src="https://i.ibb.co/2dHVrLM/cb589adc50376fda1ebc6e9404b08852-w2500-h1006.png" alt="cb589adc50376fda1ebc6e9404b08852-w2500-h1006" border="0" style="height: 60px; vertical-align:middle; display:flow-root"></a>
            <h1>Encuesta WEBER</h1>
            <p>Para poder compartir con más gente como tú nuestros talleres, te agradecemos nos compartas la siguiente información.</p>
        </div>

        <hr />

        <form>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="nombre" class="control-label">Fecha:</label>
                        <input type="date" class="form-control" id="fecha" name="fecha" required value="@ViewBag.InfoUsuario.FechaNacimiento">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="nombre" class="control-label">Nombre:</label>
                        <input type="text" class="form-control" id="nombre" name="nombre" required value="@ViewBag.InfoUsuario.Nombre">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="correo" class="control-label">Correo electrónico:</label>
                        <input type="email" class="form-control" id="correo" name="correo" required value="@ViewBag.InfoUsuario.Correo">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="nombre" class="control-label">Teléfono:</label>
                        <input type="text" class="form-control" id="telefono" name="telefono" required value="@ViewBag.InfoUsuario.TelefonoMovil">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="cp" class="control-label">C.P:</label>
                        <input type="number" class="form-control" id="cp" name="cp" required value="@ViewBag.InfoUsuario.CP">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="edad" class="control-label">Edad:</label>
                        <input type="number" class="form-control" id="edad" name="edad" required>
                    </div>
                </div>
            </div>
            <div class="row custom-padding">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="q1" class="control-label">
                            1.¿Cómo te enteraste de este taller?
                        </label>
                        <select class="form-control" id="q1" required>
                            <option value="">Selecciona una opción</option>
                            @foreach (var item1 in ViewBag.q1)
                            {
                                <option value="@item1.Id">@item1.Nombre</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
            <div class="row custom-padding">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="q2" class="control-label">
                            2.¿Cada cuándo asas?
                        </label>
                        <select class="form-control" id="q2" required>
                            <option value="">Selecciona una opción</option>
                            @foreach (var item1 in ViewBag.q2)
                            {
                                <option value="@item1.Id">@item1.Nombre</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
            <div class="row custom-padding">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="q3" class="control-label">
                            3.¿Volverías a otro taller con nosotros?
                        </label>
                        <select class="form-control" id="q3" required>
                            <option value="">Selecciona una opción</option>
                            @foreach (var item1 in ViewBag.q3)
                            {
                                <option value="@item1.Id">@item1.Nombre</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
            <div class="row custom-padding">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="q4" class="control-label text-center">4.Si te enteraste por Facebook o instagram, ¿Qué te llamó la atención de nuestra publicación?</label>
                        <input type="text" class="form-control" id="q4" required>
                    </div>
                </div>
            </div>
            <div class="row custom-padding">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="q5" class="control-label text-center">5.¿Hay algo que podamos mejorar?</label>
                        <input type="text" class="form-control" id="q5" required>
                    </div>
                </div>
            </div>
            <div class="row custom-padding">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="q6" class="control-label text-center">6.Te gustaría que te contactáramos con ofertas exclusivas, eventos y promociones?</label>
                        <select class="form-control" id="q6" required>
                            <option value="">Selecciona una opción</option>
                            <option value="0">No</option>
                            <option value="1">Si</option>
                        </select>
                    </div>
                </div>
            </div>




            <div class="text-center">
                <h3>¡Gracias por acompañarnos en esta experiencia!</h3>

                <a class="btn btn-primary" onclick="Guardar();">Guardar</a>

                
            </div>
        </form>


    </div>



</body>
</html>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<script type="text/javascript">

       function Guardar() {
        var obj = {};
        obj['IdVenta'] = @Request.QueryString["Id"];
        obj['Q1'] = $("#q1 option:selected").val();
        obj['Q2'] = $("#q2 option:selected").val();
        obj['Q3'] = $("#q3 option:selected").val();

        obj['Q4t'] = $("#q4").val();
        obj['Q5t'] = $("#q5").val();


        obj['Q6'] = $("#q6 option:selected").val();
        var jsonObject = {
            "DEncuesta": obj
        };
         $.ajax({
            type: "POST",
            url: "@Url.Action("RegistrarEncuesta", "Encuestas")",
            async: false,
            data: JSON.stringify(jsonObject),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
             success: function (data) {
                swal({
                    title: "Registro exitoso",
                    text: '',
                    icon: "success",
                    button: "Aceptar",
                }).then((value) => {
                        window.location.href = '@Url.Action("Login", "Login")';
                });


             }
        });
       }
</script>