CRMRetail/Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static System.Net.Mime.MediaTypeNames;
using System.Xml.Linq;
using m = CRMRetail.Modelos;

namespace CRMRetail.Controllers
{
    public class VentasController : Utilidades.Comun
    {
        public ActionResult Index()
        {
            if (ConsultaSesion())
            {
                List<m.Consultas.Venta_TOP> Ventas = n.venta.Venta_Selecionar();
                ViewBag.Ventas = Ventas;

                return View();
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
        }

        public ActionResult purchase()
        {
            if (ConsultaSesion())
            {
                // Obtener el valor de la sesión "Usuario" en otro controlador
                var musuariorol = (m.UsuariosRoles)Session["Usuario"];

                // Acceder al ID de usuario
                int idUsuario = musuariorol.Usuarios.Id;
                ViewBag.IdUser = idUsuario;


                List<m.Cliente> clientes = n.cliente.Cliente_Seleccionar();
                List<m.Producto> productos = n.producto.Producto_Seleccionar();
                List<m.Catalogos> Horarios = n.catHorarios.Seleccionar();
                ViewBag.CatEstados = n.catEstados.Seleccionar();

                ViewBag.Sucursales = n.catSucursal.Seleccionar();
                //INFORMACION CLIENTES
                ViewBag.Clientes = clientes;
                ViewBag.Productos = productos;
                ViewBag.Horario = Horarios;

                return View();
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
        }
        //AGREGA DATOS DE SESION PRODUCTO
        [HttpPost]
        public JsonResult AgregarProducto(m.VentaProducto ventaProducto)
        {
            List<m.NuevoProductoVenta> LstNuevosProductoVenta = new List<m.NuevoProductoVenta>();

            if (Session["VentaProducto"] != null)
            {
                LstNuevosProductoVenta = (List<m.NuevoProductoVenta>)Session["VentaProducto"];
            }

            int busqueda = 0;
            foreach (var dtProducto in LstNuevosProductoVenta)
            {
                // SI EL VALOR ES EL MISMO, SOLO ACTUALIZAMOS LA CANTIDAD.
                if(dtProducto.IdProducto == ventaProducto.IdProducto)
                {
                    dtProducto.Cantidad += ventaProducto.Cantidad;
                    busqueda = 1;
                }
            }
            
            // SI EL PRODUCTO ES NUEVO
            if(busqueda == 0)
            {
                // LISTADO DE PRECIOS QUE TIENE DISPONIBLE EL NUEVO PRODUCTO
                List<m.Catalogos> cat_precios = n.producto.Producto_Precios_Listar_Nombres(ventaProducto.IdProducto);
                // INFORMACION DEL PRODUCTO
                m.Producto producto = new m.Producto();
                producto.Id = ventaProducto.IdProducto;
                producto = n.producto.Producto_Seleccionar_Id(producto);

                m.NuevoProductoVenta jsonObject = new m.NuevoProductoVenta()
                {
                    IdProducto = producto.Id,
                    Producto = new
                    {
                        Nombre = producto.Nombre,
                        SKU = producto.SKU,
                    },
                    Cantidad = ventaProducto.Cantidad,
                    CatPrecios = cat_precios,
                    IdCatPrecios = 2,
                    Precio = producto.PrecioPublico,
                    BackOrder = 0,
                };

                LstNuevosProductoVenta.Add(jsonObject);
            }
            

            Session["VentaProducto"] = LstNuevosProductoVenta;

            /*/ RETORNAR TODA LA LISTA DE OBJETOS.
            * IdProducto
            * Nombre del producto y SKU
            * Cantidad
            * Cat_precios
            * IdCatPrecios
            * Precio unitario
            * Precio Total
            */

            return Json(LstNuevosProductoVenta);
        }

        [HttpPost]
        public JsonResult ConsultaProductosAgregados()
        {
            List<m.NuevoProductoVenta> LstNuevosProductoVenta = new List<m.NuevoProductoVenta>();

            if (Session["VentaProducto"] != null)
            {
                LstNuevosProductoVenta = (List<m.NuevoProductoVenta>)Session["VentaProducto"];
            }
            return Json(LstNuevosProductoVenta);
        }


        [HttpPost]
        public JsonResult ConsultaPrecio(m.VentaProducto ventaProducto)
        {
            List<m.NuevoProductoVenta> LstNuevosProductoVenta = new List<m.NuevoProductoVenta>();

            if (Session["VentaProducto"] != null)
            {
                LstNuevosProductoVenta = (List<m.NuevoProductoVenta>)Session["VentaProducto"];
            }
            
            // CONSULTA LOS NUEVOS VALORES
            m.Producto producto = n.producto.Producto_Selecionar_Precio(ventaProducto.IdPrecio, ventaProducto.IdProducto);

            foreach (var dtProducto in LstNuevosProductoVenta)
            {
                if(dtProducto.IdProducto == ventaProducto.IdProducto)
                {
                    dtProducto.IdCatPrecios = ventaProducto.IdPrecio;
                    dtProducto.Precio = producto.Precio;
                }
            }

            Session["VentaProducto"] = LstNuevosProductoVenta;
            
            return Json(producto);
        }

        [HttpPost]
        public JsonResult ActulizarCantidad(m.VentaProducto ventaProducto)
        {
            List<m.NuevoProductoVenta> LstNuevosProductoVenta = new List<m.NuevoProductoVenta>();

            if (Session["VentaProducto"] != null)
            {
                LstNuevosProductoVenta = (List<m.NuevoProductoVenta>)Session["VentaProducto"];
            }

            // CONSULTA LOS NUEVOS VALORES
            foreach (var dtProducto in LstNuevosProductoVenta)
            {
                if (dtProducto.IdProducto == ventaProducto.IdProducto)
                {
                    dtProducto.Cantidad = ventaProducto.Cantidad;
                }
            }

            Session["VentaProducto"] = LstNuevosProductoVenta;

            return Json(ventaProducto);
        }

        [HttpPost]
        public JsonResult ActulizarPrecio(m.VentaProducto ventaProducto)
        {
            List<m.NuevoProductoVenta> LstNuevosProductoVenta = new List<m.NuevoProductoVenta>();
            if (Session["VentaProducto"] != null)
            {
                LstNuevosProductoVenta = (List<m.NuevoProductoVenta>)Session["VentaProducto"];
            }

            // CONSULTA LOS NUEVOS VALORES
            foreach (var dtProducto in LstNuevosProductoVenta)
            {
                if (dtProducto.IdProducto == ventaProducto.IdProducto)
                {
                    dtProducto.Precio = ventaProducto.Precio;
                }
            }

            Session["VentaProducto"] = LstNuevosProductoVenta;
            return Json(ventaProducto);
        }

        [HttpPost]
        public JsonResult ActualizarBackOrder(m.VentaProducto ventaProducto)
        {
            List<m.NuevoProductoVenta> LstNuevosProductoVenta = new List<m.NuevoProductoVenta>();
            if (Session["VentaProducto"] != null)
            {
                LstNuevosProductoVenta = (List<m.NuevoProductoVenta>)Session["VentaProducto"];
            }

            // CONSULTA LOS NUEVOS VALORES
            foreach (var dtProducto in LstNuevosProductoVenta)
            {
                if (dtProducto.IdProducto == ventaProducto.IdProducto)
                {
                    dtProducto.BackOrder = ventaProducto.BackOrder;
                }
            }

            Session["VentaProducto"] = LstNuevosProductoVenta;
            return Json(ventaProducto);
        }
        //ELIMINA DATOS DE SESION PRODUCTO
        [HttpPost]
        public JsonResult EliminarProducto(m.VentaProducto ventaProducto)
        {
            List<m.NuevoProductoVenta> LstNuevosProductoVenta = new List<m.NuevoProductoVenta>();
            if (Session["VentaProducto"] != null)
            {
                LstNuevosProductoVenta = (List<m.NuevoProductoVenta>)Session["VentaProducto"];
            }

            for(int a = 0; a < LstNuevosProductoVenta.Count; a++)
            {
                if (LstNuevosProductoVenta[a].IdProducto == ventaProducto.IdProducto)
                {
                    LstNuevosProductoVenta.RemoveAt(a);
                }
                
            }

            Session["VentaProducto"] = LstNuevosProductoVenta;
            return Json(LstNuevosProductoVenta);
        }

        [HttpPost]
        public JsonResult RNuevaDireccion(m.Direccion data)
        {

           var r = n.direccion.RegistroDireccionFlash(data); 

            Session["DireccionCliente"] = r;
             
            return Json(r);
        }
        [HttpPost]
        public JsonResult verificar(m.Cliente data)
        {

            var r = n.cliente.Consultar_tipoCliente(data);

            return Json(r);
        }

        public JsonResult Taller(m.Cliente data)
        {

            var r = n.cliente.Consultar_taller (data);

            return Json(r);
        }

        //1
        [HttpPost]
        public JsonResult Direcciones_Seleccionar_List_IdCliente(m.Cliente cliente)
        {
            m.Direccion DireccionCliente = new m.Direccion();
            List<m.Direccion> direccion = n.direccion.Direcciones_Seleccionar_List_IdCliente(cliente);

            if (Session["DireccionCliente"] != null)
            {
                DireccionCliente = (m.Direccion)Session["DireccionCliente"];

                foreach (var dtdireccion in direccion)
                {
                    // SI EL VALOR ES EL MISMO, SOLO ACTUALIZAMOS LA CANTIDAD.

CRMRetail/Views/Ventas/Index.cshtml
@model List<CRMRetail.Modelos.Ventas>
@{
    ViewBag.Title = "Index";
}

<script>

    $(document).ready(function () {

        $('#IndexVentas').addClass("nav-item active submenu");

        $('#tabla01').DataTable({
            "searching": true,
            "paging": true,
            "ordering": false,
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
            },
            info: true,
        });

    });

</script>

<script src="~/assets/js/plugin/datatables/datatables.min.js"></script>
@*<script src="../assets/js/plugin/datatables/sum().js"></script>
<script src="~/assets/js/plugin/datatables/dataTables.colReorder.min.js"></script>
<link href="~/assets/css/colReorder.dataTables.min.css" rel="stylesheet" />
<link href="~/assets/css/jquery.dataTables.min.css" rel="stylesheet" />*@

<style>
    table.dataTable thead tr {
        background-color: #1f1e2e;
        color: white
    }

    .header th {
        height: 25px;
        line-height: 2px;
    }

    .logo-header[data-background-color="dark"] {
        background: #000000 !important;
    }

    .navbar-header[data-background-color="dark"] {
        background: #000000 !important;
        /*background: linear-gradient(to right, #4194BC, #70E7AF) !important;*/
        box-shadow: 4px 4px 10px rgb(69 65 78 / 71%);
    }

    .sidebar[data-background-color="dark"] {
        background: #000000 !important;
    }

    .sidebar .nav.nav-warning > .nav-item.active a i, .sidebar[data-background-color="white"] .nav.nav-warning > .nav-item.active a i {
        color: #ed1d24 !important;
    }

    .sidebar .nav.nav-warning > .nav-item.active a:before, .sidebar[data-background-color="white"] .nav.nav-warning > .nav-item.active a:before {
        background: #ed1d24 !important;
    }

    .sidebar[data-background-color="dark"] .nav > .nav-item.active > a p {
        color: #ffffff !important;
    }

    .sidebar .nav > .nav-item a p, .sidebar[data-background-color="white"] .nav > .nav-item a p {
        font-size: 14px;
        margin-bottom: 0px;
        margin-right: 5px;
        white-space: nowrap;
        color: #ffffff;
    }

    .sidebar[data-background-color="dark"] .nav > .nav-item a {
        color: #ffffff !important;
    }

    .sidebar .nav > .nav-item a i, .sidebar[data-background-color="white"] .nav > .nav-item a i {
        color: #ffffff;
        margin-right: 15px;
        width: 25px;
        text-align: center;
        vertical-align: middle;
        float: left;
        font-size: 18px;
        line-height: 30px;
    }

    .sidebar .nav.nav-warning > .nav-item a:hover i, .sidebar .nav.nav-warning > .nav-item a:focus i, .sidebar .nav.nav-warning > .nav-item a[data-toggle=collapse][aria-expanded=true] i, .sidebar[data-background-color="white"] .nav.nav-warning > .nav-item a:hover i, .sidebar[data-background-color="white"] .nav.nav-warning > .nav-item a:focus i, .sidebar[data-background-color="white"] .nav.nav-warning > .nav-item a[data-toggle=collapse][aria-expanded=true] i {
        color: #ed1d24 !important;
    }

    .sidebar .nav > .nav-item.submenu, .sidebar[data-background-color="white"] .nav > .nav-item.submenu {
        background: rgb(58 0 0);
    }

    .sidebar[data-background-color="dark"] .nav > .nav-item a:hover p, .sidebar[data-background-color="dark"] .nav > .nav-item a:focus p, .sidebar[data-background-color="dark"] .nav > .nav-item a[data-toggle=collapse][aria-expanded=true] p {
        color: #f5f5f5 !important;
    }

    .sidebar, .sidebar[data-background-color="white"] {
        position: fixed;
        top: 0;
        bottom: 0;
        left: 0;
        /*
    width: 250px;
    margin-top: 62px;
    display: block;
    z-index: 1000;
    color: #ffffff;
    font-weight: 200;
    background: #ffffff;
    */
        -webkit-box-shadow: 4px 4px 10px rgb(69 65 78 / 6%);
        -moz-box-shadow: 4px 4px 10px rgba(69, 65, 78, 0.06);
        box-shadow: 4px 4px 10px rgb(69 65 78 / 71%);
        transition: all .3s;
    }

    table.dataTable thead tr {
        background-color: #000000;
        color: white;
        font-size: 12px;
    }

    table.dataTable tr {
        font-size: 13px;
    }

    .btn-link:hover {
        color: #810f13;
        text-decoration: underline;
        background-color: transparent;
        border-color: transparent;
    }

    .btn-link {
        font-weight: 400;
        color: #ed1d24;
        background-color: transparent;
    }

    .page-item.active .page-link {
        z-index: 1;
        color: #fff;
        background-color: #de1b22;
        border-color: #df1b22;
    }

    .nav-pills.nav-secondary .nav-link.active {
        background: #ed1d24;
        border: 1px solid #6861CE;
    }
</style>


<div class="page-inner">


    <div class="page-header">
        <h4 class="page-title">Ventas</h4>
        <ul class="breadcrumbs">
            <li class="nav-home">
                <a href="#">
                    <i class="flaticon-home"></i>
                </a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="#">Venta</a>
            </li>
        </ul>
    </div>

    <div class="row">
        <div class="col-md-9">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Listado de ventas registradas </div>
                    <div class="card-category">Visualiza la información de una venta al dar clic sobre el icono  <i class="fa fa-eye" aria-hidden="true"></i></div>

                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="table-responsive">
                            <table id="tabla01" class="display compact hover table-striped table-hover text-center" style="width:100%;">
                                <thead class="header">
                                    <tr>
                                        <th>Fecha</th>
                                        <th>Nombre </th>
                                        <th>Monto </th>
                                        <th>Sucursal </th>
                                        <th>Estatus </th>
                                        <th>Visualizar</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        foreach (var dtCliente in ViewBag.Ventas)
                                        {
                                            if (@dtCliente.Estatus == "Back Order")
                                            {
                                                <tr style="background-color:#ffd800">
                                                    <td>@dtCliente.FechaRegistro</td>
                                                    <td>@dtCliente.Nombre</td>
                                                    <td>$@string.Format("{0:N}", @dtCliente.Monto)</td>
                                                    <td>@dtCliente.Sucursal</td>
                                                    <td>@dtCliente.Estatus</td>
                                                    <td>
                                                        
                                                    <button type="button" class="btn btn-icon btn-link" onclick="ConsultaVenta(@dtCliente.Id)">
                                                        <i class="fa fa-eye"></i>
                                                    </button>
                                                     </td>
                                                </tr>
                                            }
                                            else
                                            {
                                                <tr>
                                                    <td>@dtCliente.FechaRegistro</td>
                                                    <td>@dtCliente.Nombre</td>
                                                    <td>$@string.Format("{0:N}", @dtCliente.Monto)</td> 
                                                    <td>@dtCliente.Sucursal</td>
                                                    <td>@dtCliente.Estatus</td>
                                                    <td>
                                                        <button type="button" class="btn btn-icon btn-link" onclick="ConsultaVenta(@dtCliente.Id)">
                                                            <i class="fa fa-eye"></i>
                                                        </button>
                                                    </td>
                                                </tr>
                                            }

                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-default" href="@Url.Action("purchase", "Ventas")">
                        <span class="btn-label">
                            <i class="fa fa-shopping-bag"></i>
                        </span>
                        Nueva venta
                    </a>
                </div>
            </div>
        </div>
    </div>

</div>

<script>

    function ConsultaVenta(id) {

        location.href = '/Ventas/Modificar?Id=' + id;

    }

</script>

CRMRetail/Views/Ventas/OrdenesPendientes.cshtml
@{
    ViewBag.Title = "OrdenesPendientes";
}

<script>

    $(document).ready(function () {

        $('#IndexVentas').addClass("nav-item active submenu");

        $.fn.dataTable.moment("DD/MM/YYYY");

        $('#tabla01').DataTable({
            "searching": true,
            "paging": true,
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
            },
            "scrollX": true,
            info: true,
        });

    });
</script>

<script src="~/assets/js/plugin/datatables/datatables.min.js"></script>
<script src="../assets/js/plugin/datatables/sum().js"></script>
<script src="~/assets/js/plugin/datatables/dataTables.colReorder.min.js"></script>
<link href="~/assets/css/colReorder.dataTables.min.css" rel="stylesheet" />
<link href="~/assets/css/jquery.dataTables.min.css" rel="stylesheet" />


<div class="page-inner">
    <div class="page-header">
        <h4 class="page-title">Ordenes Pendientes</h4>
    </div>

    <div class="card">

        <div class="card-body">

            <div class="row">

                <div class="col-md-12 text-right">

                    <a href="/Ventas/Index">Todos las Ventas</a>

                </div>

            </div>

        </div>

    </div>

    <div class="card">

        <div class="card-body">

            <div class="row">

                <div class="table-responsive">
                    <table id="tabla01" class="display compact hover" style="width:100%">
                        <thead class="header">
                            <tr>
                                <th>Nombre</th>
                                <th>RFC</th>
                                <th>Fecha&nbsp;Venta</th>
                                <th>Tipo&nbsp;Venta</th>
                                <th>Tipo&nbsp;Entrega</th>
                                <th>Vendedor</th>
                                <th>Monto</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>

                            @if (Model == null)
                            {
                                <tr><td colspan="7" align="center">Sin datos para mostrar</td></tr>
                            }
                            @foreach (var items in Model)
                            {

                                <tr>
                                    <td>@items.Clientes.Nombre @items.Clientes.ApellidoPaterno @items.Clientes.ApellidoMaterno</td>
                                    <td>@items.Clientes.RFC</td>
                                    <td>@items.Fecha.ToString("dd/MM/yy")</td>
                                    <td>@CRMRetail.Datos.Catalogos.SeleccionarNombrePorId(items.Tipo.ToString(), "TipoVenta")</td>
                                    <td>@CRMRetail.Datos.Catalogos.SeleccionarNombrePorId(items.TipoEntrega.ToString(), "TipoEntrega")</td>
                                    <td>@CRMRetail.Datos.Catalogos.SeleccionarNombrePorId(items.Usuarios.Id.ToString(), "Usuarios")</td>
                                    <td align="right"><a href="#" onclick="ModalDetalle(@items.Id);">@items.Monto.ToString("c")</a></td>
                                    <td align="center"><a href="/Ventas/Modificar?id=@items.Id"><i class="fas fa-pencil-alt"></i></a></td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>


            </div>

        </div>

    </div>

</div>

CRMRetail/Views/Ventas/ProductosXCliente.cshtml
@model List<CRMRetail.Modelos.VentasGeneral>
@{
    ViewBag.Title = "Productos X Cliente";
}

<script>

    $(document).ready(function () {

        $('#IndexVentas').addClass("nav-item active submenu");

        $.fn.dataTable.moment("DD/MM/YYYY");

        $('#tabla01').DataTable({
            "searching": true,
            "paging": true,
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
            },
            "scrollX": true,
            info: true,
        });

    });

</script>

<script src="~/assets/js/plugin/datatables/datatables.min.js"></script>
<script src="../assets/js/plugin/datatables/sum().js"></script>
<script src="~/assets/js/plugin/datatables/dataTables.colReorder.min.js"></script>
<link href="~/assets/css/colReorder.dataTables.min.css" rel="stylesheet" />
<link href="~/assets/css/jquery.dataTables.min.css" rel="stylesheet" />

<div class="page-inner">
    <div class="page-header">
        <h4 class="page-title">Productos X Cliente</h4>
    </div>

    <div class="card">

        <div class="card-body">

            <div class="row">

                <div class="col-md-12 text-right">

                    <a href="/Ventas/Index">Todos las Ventas</a>

                </div>

            </div>

        </div>

    </div>

    <div class="card">

        <div class="card-body">

            <div class="row">

                <div class="table-responsive">
                    <table id="tabla01" class="display compact hover" style="width:100%">
                        <thead class="header">
                            <tr>
                                <th>Id</th>
                                <th>Nombre</th>
                                <th>SKU</th>
                                <th>Fecha&nbsp;Venta</th>
                                <th>Cliente</th>
                            </tr>
                        </thead>
                        <tbody>

                            @if (Model == null)
                            {
                                <tr><td colspan="5" align="center">Sin datos para mostrar</td></tr>
                            }
                            @foreach (var items in Model)
                            {
                                <tr>
                                    <td>@items.Productos.Id</td>
                                    <td>@items.Productos.Nombre</td>
                                    <td>@items.Productos.SKU</td>
                                    <td>@items.Ventas.Fecha.ToString("dd/MM/yy")</td>
                                    <td>@items.Clientes.Nombre</td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>


            </div>

        </div>

    </div>

</div>

CRMRetail/Views/Ventas/VentasPorCategoria.cshtml
@model List<CRMRetail.Modelos.VentasProductos>
@{
    ViewBag.Title = "Ventas Por Categoria";
}

<script>

    $(document).ready(function () {

        $('#IndexVentas').addClass("nav-item active submenu");

        $.fn.dataTable.moment("DD/MM/YYYY");

        $('#tabla01').DataTable({
            "searching": true,
            "paging": true,
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
            },
            "scrollX": true,
            info: true,
        });

    });

    function ObtenerVentasPorCategoria() {
        //alert($('#Categoria').val());
        $.ajax({
            type: "GET",
            url: "/Ventas/VentasProductosObtenerPorCategoria/",
            data: { idcategoria: $('#Categoria').val() },
            contentType: "application/json",
            dataType: "json",
            success: function (data) {

                $('#tabla01 tbody tr').remove();
                $('#tabla01').append('<tbody>');
                for (var i = 0; i < data.length; i++) {

                    var fecha = new Date(parseInt(data[i].Fecha.substr(6)));
                    var mes = (fecha.getMonth() + 1) < 10 ? '0' + (fecha.getMonth() + 1) : (fecha.getMonth() + 1);

                    $('#tabla01').append(
                        '<tr><td>' + data[i].Productos.Nombre +
                        '</td><td align=center>' + data[i].Productos.SKU +
                        '</td><td align=center>' + data[i].NombreCategoria +
                        '</td><td align=right>$' + (Math.round(data[i].Precio * 100) / 100).toFixed(2) +
                        '</td><td align=right>' + fecha.getDate() + '/' + mes + '/' + fecha.getFullYear() +
                        '</td></tr>');
                }
                $('#tabla01').append('</tbody>');
            },
            error: function (jqXHR, textStatus, errorThrown) {
                console.log('jqXHR:');
                console.log(jqXHR);
                console.log('textStatus:');
                console.log(textStatus);
                console.log('errorThrown:');
                console.log(errorThrown);
            }
        });


    }

</script>

<script src="~/assets/js/plugin/datatables/datatables.min.js"></script>
<script src="../assets/js/plugin/datatables/sum().js"></script>
<script src="~/assets/js/plugin/datatables/dataTables.colReorder.min.js"></script>
<link href="~/assets/css/colReorder.dataTables.min.css" rel="stylesheet" />
<link href="~/assets/css/jquery.dataTables.min.css" rel="stylesheet" />

<div class="page-inner">
    <div class="page-header">
        <h4 class="page-title">Ventas Por Categoría</h4>
    </div>

    <div class="card">

        <div class="card-body">

            <div class="row">

                <div class="col-md-12 text-right">

                    <a href="/Ventas/Index">Todos las Ventas</a>

                </div>

            </div>

        </div>

    </div>

    <div class="card">

        <div class="card-body">

            <!--div class="row">

                <div class="col-md-4">
                    <div class="form-group form-floating-label">
                        <select class="form-control input-solid" id="Categoria" name="Categoria" onchange="ObtenerVentasPorCategoria();">
                            <option value=""></option>
                            @foreach (var item1 in CRMRetail.Datos.Catalogos.Seleccionar("ProductosCategoria"))
                            {
                                <option value="@item1.Id">@item1.Nombre</option>
                            }
                        </select>
                        <label for="Categoria" class="placeholder">Categoría</label>
                    </div>
                </div>

            </div-->

            <div class="row">

                <div class="table-responsive">
                    <table id="tabla01" class="display compact hover" style="width:100%">
                        <thead class="header">
                            <tr>
                                 <th>Nombre</th>
                                <th>SKU</th>
                                <th>Categoría</th>
                                <th>Precio</th>
                                <th>Fecha</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            @foreach (var items in Model)
                            {
                                <tr>
                                    <td>@items.Productos.Nombre</td>
                                    <td align="right">@items.Productos.SKU</td>
                                    <td>@items.NombreCategoria</td>
                                    <td align="right">@items.Precio.ToString("c")</td>
                                    <td align="right">@items.Fecha.ToString("dd/MM/yy")</td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>


            </div>

        </div>

    </div>

</div>